apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  labels:
    app: sentinel
spec:
  selector:
    app: sentinel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-api
  type: ClusterIP # Use LoadBalancer for external access in cloud environments
